--------------------------------------------------------
--  File created - Thursday-June-01-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LANDPLOT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."LANDPLOT" 
   (	"LAND_PLOT_ID" VARCHAR2(20 BYTE), 
	"WATER_AMOUNT" FLOAT(126), 
	"TIME_SLOT" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.LANDPLOT
SET DEFINE OFF;
Insert into SYSTEM.LANDPLOT (LAND_PLOT_ID,WATER_AMOUNT,TIME_SLOT) values ('2',20.56,10);
Insert into SYSTEM.LANDPLOT (LAND_PLOT_ID,WATER_AMOUNT,TIME_SLOT) values ('3',20.56,0);
Insert into SYSTEM.LANDPLOT (LAND_PLOT_ID,WATER_AMOUNT,TIME_SLOT) values ('4',20.56,5);
Insert into SYSTEM.LANDPLOT (LAND_PLOT_ID,WATER_AMOUNT,TIME_SLOT) values ('21',4.5,6);
Insert into SYSTEM.LANDPLOT (LAND_PLOT_ID,WATER_AMOUNT,TIME_SLOT) values ('22',4.5,6);
Insert into SYSTEM.LANDPLOT (LAND_PLOT_ID,WATER_AMOUNT,TIME_SLOT) values ('23',4.5,6);
Insert into SYSTEM.LANDPLOT (LAND_PLOT_ID,WATER_AMOUNT,TIME_SLOT) values ('24',4.5,6);
Insert into SYSTEM.LANDPLOT (LAND_PLOT_ID,WATER_AMOUNT,TIME_SLOT) values ('25',4.5,6);
--------------------------------------------------------
--  DDL for Index LANDPLOT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."LANDPLOT_PK" ON "SYSTEM"."LANDPLOT" ("LAND_PLOT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LANDPLOT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LANDPLOT" MODIFY ("LAND_PLOT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LANDPLOT" MODIFY ("WATER_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LANDPLOT" ADD CONSTRAINT "LANDPLOT_PK" PRIMARY KEY ("LAND_PLOT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
